#!/bin/sh
if [ -z "$1" ] ||  [ -z "$2" ]
then
        echo "Usage: $0 <workDir> <headerFileName>"
        exit 1;
fi
TMPSVNFILE=.tmpsvnfile.$$
svnversion -h 1>/dev/null 2>&1
if [ $? -ge 1 ]
then
        echo "svnversion is not installed!!!" >/dev/stderr
        echo "Automatic $2 generation will not produce correct results!!!" >/dev/stderr
        SVNV="UNKNOWN"
else
        SVNV=`svnversion $1`
fi

echo "// Autogenerated file! Do not edit! Do not add to svn repository!" > "$TMPSVNFILE"
echo "#define SVN_REVISION \"$SVNV\"" >> "$TMPSVNFILE"

if [ ! -f $2 ]
then
        DOMAKE=1
else
        diff -w -a "$TMPSVNFILE" "$2" 1>/dev/null 2>&1
        if [ $? -ge 1 ]
        then
                DOMAKE=1
        fi
fi
if [ -z "$DOMAKE" ]
then
        rm "$TMPSVNFILE" 1>/dev/null 2>&1
        echo "Revision $SVNV was not changed since last run. File $2 remains untouched.">/dev/stderr
        exit 0;
fi

rm "$2" 1>/dev/null 2>&1
cp "$TMPSVNFILE" "$2" 1>/dev/null 2>&1
if [ $? -ge 1 ]
then
        echo "Can not copy $TMPSVNFILE into $2" >/dev/stderr
        exit 1;
fi
rm "$TMPSVNFILE" 1>/dev/null 2>&1
echo "File $2 was updated with svn revision $SVNV" >/dev/stderr
exit 0;


